### ISSUE TITLE
symfony crawler

### ISSUE THREAD

**Issue by masihfathi** [justacan/cloudflare#3]
thanks for great code is it possible to sync code with symfony crawler?

**Comment by justacan** [comment]
Thanks you for your interest in this project.
I have not looked into Symfony Crawler, but if you can catch the 503 errors, and use this:

```
             $cloudflare = new CloudFlare($this->body); // create CloudFlare instance 
            if ($cloudflare->detect()) { // bool if CloudFlare
                $cloudflare->addBaseUrl($this->baseUrl); // the JavaScript needs the baseUrl
                $cfo = $cloudflare->challengeForm(); // CloudFlare challengeForm answers
                $this->makeRequest($cfo->url, $cfo->query); // send it back in the query string
                sleep(5); // must wait 5 seconds
                $this->makeRequest($page, array(), true); // try the origial page again
            }
```

Then return the body to the crawler, and continue using the cookie

**Comment by justacan** [comment]
However looking at Symfony Crawler, it seems to just want HTML, after getting the page back, just pass it into it. I pretty much just use [PHP:DOM](http://php.net/manual/en/book.dom.php) and it looks like SC is a wrapper for it

**Comment by masihfathi** [comment]
i want for example get a form with symfony crawler and submit form and for example click on a link then. is it possible to do this without using symfony and just use guzzle?

**Comment by justacan** [comment]
After getting past cloudFlare, and if you know the form action address and the data you want to submit to the form, you could add this method the example code:

```
public function submitForm($page, $query = array(), $form_params = array(), $debug) {
        try {
            $options = [
              'headers' => [
                'User-Agent' => 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36',
                'Host' => $this->host,
                'Referer' => $this->baseUrl . $page
              ]
            ];

            if (!empty($query)) {
                $options['query'] = $query;
            }

            if (!empty($form_params)) {
                $options['form_params'] = $form_params;
            }

            $res = $this->client->request('POST', $this->baseUrl . $page, $options);
            $this->body = $res->getBody();

            return true; //everything is fine
        } catch (RequestException $e) {
            if ($e->getCode() === 503) { // might be CloudFlare
                $this->body = $e->getResponse()->getBody(); // set body to var
                return false;
            }
        }
    }
```

```
$form_params = array("first_name" => "test", "last_name" => "guy");
$browser = new Browser("http://example.com", "example.com");
$browser->submitForm('/formAction', array(), $form_params, true);
```
[http://guzzle.readthedocs.io/en/latest/request-options.html?highlight=getconfig#form-params](http://guzzle.readthedocs.io/en/latest/request-options.html?highlight=getconfig#form-params)

**Comment by masihfathi** [comment]
thanks for your help. first i try to use your code with a site without cloud flare like github but my login did not authenticated and i didn't get https://github.com/settings/profile which need login, in the browser class config i use cookie file,  
```
$path = __DIR__ . '/tmp/cookie.txt';
$this->jar = new FileCookieJar($path, TRUE);
$this->client = new Client(['cookies' => $this->jar, 'allow_redirects' => true]);
```
in the __construct of Browser class, but i dont know why my authentication failed and i did not see https://github.com/settings/profile page.

```
require_once 'vendor/autoload.php';
require_once 'Browser.php';
$browser = new Browser("https://github.com", "github.com");
$form_params = ["login" => "user", "password" => "pass"];
$browser->submitForm('/session', array(), $form_params, true);
$browser->getPage('/settings/profile');
$browser->saveBody();
```

i really thank you to check this issue

**Comment by masihfathi** [comment]
thanks for your extension.
i want to submit a login form for example github login page and then do a request to page which need login for example "https://github.com/settings/profile" and get that page. i have not found a solution with only guzzle package.i do a lot work on mixing "https://github.com/FriendsOfPHP/Goutte " package with your code(this package use "https://github.com/symfony/browser-kit" to submit form and handle requests, this package can login with login form and ...), but i have not found a solution, cause Goutte use symfony browser kit to handle requests and i have not found a solution on how to handle request again on doRequest method of symfony browser kit when cloud flare page shown up. 
do you have any idea on how to do login with login form with your package? or any idea on how to solve this problem.
thanks a lot
